[package]
name = "gpui_tokio"
version = "0.1.0"
license = "Apache-2.0"
edition = "2024"

[lib]
path = "src/gpui_tokio.rs"
doctest = false

[dependencies]
anyhow.workspace = true
gpui.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }